# -*- coding: utf-8 -*-
"""lautaroPracticoDos.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bW3vUPO_3X-wCJ2osGz2R3hKsE06iofX
"""

numeros = []
for i in range (10):
  resultado = int(input("inserte su numero: "))
  numeros.append(resultado)

numeros_pares = []

for numero in numeros:
    if numero % 2 == 0:

        numeros_pares.append(numero)

print("Números pares:", numeros_pares)

import re
from collections import Counter

def contar_pronombres(texto):

    pronombres = [
        'yo', 'tú', 'él', 'ella', 'nosotros', 'nosotras', 'vosotros', 'vosotras',
        'ellos', 'ellas', 'usted', 'ustedes', 'me', 'te', 'lo', 'la', 'nos', 'os', 'los', 'las',
        'le', 'les', 'mi', 'tu', 'su', 'nuestro', 'nuestra', 'vuestro', 'vuestra', 'mío', 'mía',
        'tuyo', 'tuya', 'suyo', 'suya', 'nuestro', 'nuestra', 'vuestro', 'vuestra'
    ]


    texto = re.sub(r'[^\w\s]', '', texto.lower())

    palabras = texto.split()


    pronombres_en_texto = [palabra for palabra in palabras if palabra in pronombres]


    conteo = Counter(pronombres_en_texto)


    total_pronombres = sum(conteo.values())

    return conteo, total_pronombres


texto = input("Ingrese su texto: ")
conteo_pronombres, cantidad_total = contar_pronombres(texto)


print(f"El texto contiene un total de {cantidad_total} pronombres.")
print("Distribución de pronombres encontrados:")
for pronombre, cantidad in conteo_pronombres.items():
    print(f"{pronombre}: {cantidad}")