# -*- coding: utf-8 -*-
"""NaiaraPracticoDos.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Tyqy_YepK3RNCFtFSA9sSJ5jKz45oRIl
"""

#aca guardo el texto de Lengua en una variable
texto = """Stéfano habita una vieja casa de barrio pobre. Él vive allí desde hace mucho tiempo.
El humilde hogar es de tres piezas; dos, dan a la calle; la otra es de madera y cinc y recuadra
con un patio lleno de viento. La casa tiene varias ventanas. La que está a la derecha lleva al
zaguán oscuro; la de la izquierda a la otra sala. La humedad es tan antigua que ya no queda ese
olor ácido y penetrante, sin embargo las huellas verdinegras perduran en las paredes y en los techos,
los cuales, crujen al compás del viento. Stéfano no tuvo en su vida lo que deseaba, sin embargo,
la carencia le ayudó a que él nunca se rindiera ante su destino. Lo único que le interesaba era
lograr lo que soñaba."""

#Lista de pronomombres que quiero buscar
pronombres = ["él", "ella", "me", "te", "se", "nos", "le", "les", "lo", "la", "los", "las"]

#Convertimos el texto a minúsculas y lo separamos el texto en palabras individuales que me sirve para contar bien las palabras sin errores.
palabras = texto.lower().split()

#Creamos un diccionario vacio para guardar los pronombres cuantas veces aparezcan
conteo = {}

#recorre cada pronombre de la lista "pronombres", cuenta cuantas veces aparece cada uno, y si aparece almenos 1 vez, lo guarda en el dicccionario conteo.
for pronombre in pronombres:
    cantidad = palabras.count(pronombre)
    if cantidad > 0:
        conteo[pronombre] = cantidad

#el primer print muestra el diccionario con los pronombres y su cantidad.
#el segundo print suma todos los valores para obtener el total de pronombres del texto.
print("Pronombres encontrados:", conteo)
print("Total de pronombres:", sum(conteo.values()))