# -*- coding: utf-8 -*-
"""NaiaraPracticoUno.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FYEPujJ_ZmUhF7l7k1LBoHCTvDf0bGJ5
"""

#cree una lista vacia para guardar los numeros
numeros = []

#bucle para pedir 10 numeros, con el range se ejecuta eso 10 veces y esos numeros se convierten en enteros.
for i in range(10):
  num = int(input("ingrese un numero:"))

#agrega los numeros ingresados a la lista (con el append) de la lista numeros para agregar el valor "num" que son los numeros que pasa el usuario.
  numeros.append(num)

#creamos otra lista para los numeros pares
pares = []

#se recorre la lista numeros, verifica si el numero n se puede dividr el numero en 2, y si el resto es igual a 0 es par y
for n in numeros:
  if n % 2 == 0:

#lo agregamos a la lista de pares
     pares.append(n)

#muetro la lista de nmros pares
print("numeros pares:", pares)

